#-------------------------------
# General Site Settings
title: Samiha Singh
# logo: logo.svg # You can add own logo.
description: Welcome to my personal portfolio.

#-------------------------------
# Author Settings
author:
  name: Samiha Singh
  image: Samiha_Headshot.jpg
  say-hello: Hello, I'm <strong>Samiha Singh</strong>
  bio: >
    Fourth-year student @UC Berkeley studying Computer Science and Business (Haas) ğŸ»
    <br>
    Focused on the intersection of entrepreneurship, technology, and social impact :)
    <br>
    Lived in ğŸ‡®ğŸ‡³, ğŸ‡¸ğŸ‡¬, and ğŸ‡ºğŸ‡¸

#-------------------------------
# Contact links
# twitter: https://twitter.com/ # Add your Twitter handle
linkedin: https://linkedin.com/in/samiha-sing # Add your Pinterest handle
twitter: https://x.com/samihasingh_

#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Instagram Feed
# instafeed: # To enable the instafeed, use the value true. To turn off use the value false.
# instagram-profile: artemsheludko_ # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e
